# Generated by Django 3.1.2 on 2020-11-12 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(max_length=200)),
                ('question_prompt', models.CharField(max_length=200)),
                ('topic_type', models.CharField(max_length=200)),
            ],
        ),
    ]
