# Generated by Django 3.1.3 on 2020-12-06 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsummary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='topic_type',
            field=models.CharField(default='', max_length=200),
        ),
    ]
