# Generated by Django 3.1.3 on 2020-11-14 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsummary', '0002_auto_20201112_0248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_notes', models.CharField(max_length=250)),
            ],
        ),
    ]
