# Generated by Django 3.1.3 on 2020-11-14 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentsummary', '0003_note'),
        ('studentsummary', '0003_topic'),
    ]

    operations = [
    ]
