# Generated by Django 3.1.3 on 2020-11-15 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsummary', '0004_merge_20201114_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestedPractice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_suggested', models.CharField(max_length=200)),
                ('topic_most_missed', models.CharField(max_length=200)),
                ('suggested_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
