# Generated by Django 3.1.3 on 2020-11-20 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsummary', '0005_suggestedpractice'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField()),
                ('topic', models.CharField(max_length=200)),
            ],
        ),
    ]
