# Generated by Django 3.1.3 on 2020-11-21 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentsummary', '0006_progresstracker'),
        ('studentsummary', '0006_student'),
    ]

    operations = [
    ]
