# Generated by Django 3.1.2 on 2020-11-22 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsummary', '0007_merge_20201121_0024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='topic_type',
        ),
        migrations.AddField(
            model_name='question',
            name='score',
            field=models.FloatField(default=0.0),
        ),
    ]
