# Generated by Django 3.1.3 on 2020-11-22 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentsummary', '0007_merge_20201121_0024'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
