# Generated by Django 3.1.2 on 2020-11-22 00:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('studentsummary', '0008_auto_20201121_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='topic_type',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
