# Generated by Django 3.1.2 on 2020-11-26 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentsummary', '0009_question_topic_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progresstracker',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentsummary.topic'),
        ),
        migrations.AlterField(
            model_name='question',
            name='topic_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentsummary.topic'),
        ),
    ]
