# Generated by Django 3.1.3 on 2020-11-26 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentsummary', '0009_question_topic_type'),
        ('studentsummary', '0008_delete_student'),
    ]

    operations = [
    ]
