# Generated by Django 3.1.2 on 2020-11-26 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentsummary', '0008_delete_student'),
        ('studentsummary', '0010_auto_20201126_1025'),
    ]

    operations = [
    ]
