# Generated by Django 3.1.3 on 2020-12-03 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentsummary', '0011_merge_20201126_1642'),
        ('studentsummary', '0011_student'),
    ]

    operations = [
    ]
