# Generated by Django 3.1.3 on 2020-11-30 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentsummary', '0011_student'),
        ('studentsummary', '0011_merge_20201126_1642'),
    ]

    operations = [
    ]
