# Generated by Django 3.1.3 on 2020-12-02 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsummary', '0012_merge_20201129_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progresstracker',
            name='topic',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='topic_type',
            field=models.CharField(max_length=200),
        ),
    ]
