# Generated by Django 3.1.3 on 2020-12-02 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentsummary', '0010_merge_20201124_2241'),
        ('studentsummary', '0013_auto_20201201_2135'),
    ]

    operations = [
    ]
