# Generated by Django 3.1.3 on 2020-12-02 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentsummary', '0014_merge_20201202_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progresstracker',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentsummary.topic'),
        ),
        migrations.AlterField(
            model_name='question',
            name='topic_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentsummary.topic'),
        ),
    ]
