# Generated by Django 3.1.2 on 2020-12-03 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsummary', '0015_auto_20201202_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progresstracker',
            name='topic',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='topic_type',
            field=models.CharField(max_length=200),
        ),
    ]
